### ISSUE TITLE
angular is not defined

### ISSUE THREAD

**Issue by santosh2221994** [angular-seattle/ng1-ng2-hybrid#3]
at Object.../../../../../src/client/ngsrc/app/downgrades.ts (downgrades.ts:13)

**Comment by jensbodal** [comment]
Can  you please provide more information? Where/when are you seeing this?

**Comment by santosh2221994** [comment]
when I serve the project using ng-serve
![screenshot 2019-02-27 at 2 06 17 pm](https://user-images.githubusercontent.com/13116284/53476642-e4d33e00-3a98-11e9-9f11-9ad1f242b5cb.png)

The error shows at the console of chrome
![screenshot 2019-02-27 at 2 07 33 pm](https://user-images.githubusercontent.com/13116284/53476723-0e8c6500-3a99-11e9-9fae-8b10893e3d58.png)

**Comment by jensbodal** [comment]
You need to use the `start` script from package.json (`npm start` or `yarn start`) to run the app, grunt runs the `ng build --watch` script to concurrently build both the angular and angularjs sources for local development. 

The actual app is served via express on port `6677`.

**Comment by santosh2221994** [comment]
Thanks. It works
Actually, I'm making a hybrid application from AngularJS(v1.4.8) to Angular. Then I want to move it all on angular can you suggest some docs.

**Comment by jensbodal** [comment]
The guide is fairly comprehensive, though was written when Angular 4 was the latest. I haven't worked on upgrading an app in some time now.  

I'd recommend looking at [page 1 in the guide](https://github.com/angular-seattle/ng1-ng2-hybrid/blob/master/guide/step-1.md) and more importantly the [official angular guide on upgrading](https://angular.io/guide/upgrade).  My guess is that there are now more recent guides and StackOverflow answers available to help you than were available when I started the process.

Good luck!
